name: hub
version: v2.14.2
summary: "hub is a command-line wrapper for git that makes you better at GitHub."
description: |
  As a contributor to open-source
  
  Whether you are beginner or an experienced contributor to open-source, hub makes it easier to fetch repositories, navigate project pages, fork repos and even submit pull requests, all from the command-line.

  As an open-source maintainer

  Maintaining a project is easier when you can easily fetch from other forks, review pull requests and cherry-pick URLs. You can even create a new repo for your next thing.

  Using GitHub for work

  Save time at work by opening pull requests for code reviews and pushing to multiple remotes at once. Even GitHub Enterprise is supported.

  Hub is made by GitHub. This snap is packaged by Ricardo N Feliciano (FelicianoTech) using the `hub` source code available by GitHub.
grade: stable
confinement: classic
icon: icon.png

parts:
  hub:
    plugin: nil
    override-build: |
      snapcraftctl build

      # The hub binary is custom compiled because a static binary is desired
      # https://github.com/felicianotech/hub-snap/pull/33
      export GOPATH=$SNAPCRAFT_PART_INSTALL/go
      export PATH=$GOPATH/bin:$PATH
      mkdir -p $GOPATH/src/github.com/github/
      cd $GOPATH/src/github.com/github/
      git clone --branch=$SNAPCRAFT_PROJECT_VERSION https://github.com/github/hub.git
      cd hub
      CGO_ENABLED=0 go build -ldflags "-X github.com/github/hub/version.Version=`./script/version`"
      cp hub $SNAPCRAFT_PART_INSTALL

      # Download the upstream release to get extras we need
      curl -sSL "https://github.com/github/hub/releases/download/v`./script/version`/hub-linux-amd64-`./script/version`.tgz" -o hub.tar.gz
      tar xfz hub.tar.gz

      # setup help/man pages
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/man/man1
      cp hub-linux-amd64-`./script/version`/share/man/man1/*.1 $SNAPCRAFT_PART_INSTALL/usr/share/man/man1/

      # setup bash completion
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/bash-completion/completions
      cp hub-linux-amd64-`./script/version`/etc/hub.bash_completion.sh $SNAPCRAFT_PART_INSTALL/usr/share/bash-completion/completions/hub
    build-packages:
      - git
apps:
  hub:
    command: hub
    environment:
      MANPATH: "/snap/hub/current/usr/share/man:$MANPATH"
    completer: "/snap/hub/current/usr/share/bash-completion/completions/hub"
